name: Build Plugin Master
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Build the plugin
        run: gradle :buildPlugin
      - name: Save the plugin
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: SpaceInvaders-plugin
          path: |
            build/distributions/SpaceInvaders-*.zip