name: Build and publish plugin
on:
  release:
    types: [published]
jobs:
  build-and-publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Build the plugin
        run: ./gradlew :buildPlugin
      - name: Save the plugin
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: SpaceInvaders-plugin
          path: |
            build/distributions/SpaceInvaders-*.zip
      - name: Upload the plugin to the release page
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'build/distributions/SpaceInvaders-*.zip'